# Concatenate feature files

In [1]:
import numpy as np
import pandas as pd
from pyhere import here
import glob
import os

In [2]:
def get_merged_files(flist, **kwargs):
    return pd.concat([pd.read_feather(f, **kwargs) for f in flist], axis=0)

## Monthly files to yearly

In [3]:
# satellite = "landsat-8-c2-l2"
# satellite = "sentinel-2-l2a"
satellite = "landsat-c2-l2"

country_code = 'ZMB' # 'TZA' # 'NGA'

# points = 15
points = 20

num_features = 1024

# bands_short = "2-3-4"
# bands_short = "2-3-4-8"
# bands_short = "1-2-3-4-5-6-7"
bands_short = "r-g-b-nir-swir16-swir22"
# bands_short = "2-3-4-5-6-7-8-11-12"

year = 2014

file_name = (f'{satellite}_bands-{bands_short}_{country_code}_{points}'+
             f'k-points_{num_features}-features_{year}')
file_name

'landsat-c2-l2_bands-r-g-b-nir-swir16-swir22_ZMB_20k-points_1024-features_2014'

In [5]:
path = str(here('data', 'random_features', 'partial_features', f'{file_name}_*.feather'))
files = glob.glob(pathname=path)
df = get_merged_files(files)
df = df.sort_values(by = ['month']).reset_index(drop = True)
df

,0,1,2,3,4,5,6,7,8,9,...,1018,1019,1020,1021,1022,1023,lon,lat,year,month
0,0.001182,0.000000,0.000000,3.561255,0.0,1.495595,0.028800,0.0,0.0,0.0,...,1.130383,0.0,0.0,0.235011,2.188993,0.000751,25.084878,-15.964232,2014,1
1,0.377920,0.000000,0.127252,3.509145,0.0,1.648901,3.269998,0.0,0.0,0.0,...,0.021633,0.0,0.0,0.757942,3.761669,0.001637,26.204878,-17.004232,2014,1
2,0.385876,0.000608,0.094160,3.984513,0.0,1.842599,1.900480,0.0,0.0,0.0,...,0.015979,0.0,0.0,0.390047,3.327730,0.004870,26.284878,-16.994232,2014,1
3,0.410757,0.010888,0.118228,3.792298,0.0,1.805657,2.329006,0.0,0.0,0.0,...,0.046064,0.0,0.0,0.439778,3.418653,0.003612,26.294878,-16.994232,2014,1
4,0.329433,0.001943,0.101390,3.549775,0.0,1.629433,1.905517,0.0,0.0,0.0,...,0.008724,0.0,0.0,0.479341,3.213167,0.000493,26.304878,-16.994232,2014,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181598,0.552910,0.000000,0.085631,3.536155,0.0,1.854955,6.015391,0.0,0.0,0.0,...,0.000000,0.0,0.0,1.189984,4.725350,0.000000,31.394878,-14.394232,2014,12
181599,0.680078,0.000000,0.143613,3.866255,0.0,2.072900,6.488448,0.0,0.0,0.0,...,0.000000,0.0,0.0,1.173612,5.001288,0.000000,31.404878,-14.384232,2014,12
181600,0.558219,0.000000,0.178471,3.583235,0.0,1.873756,6.061517,0.0,0.0,0.0,...,0.000000,0.0,0.0,1.227787,4.817301,0.000000,31.384878,-14.364232,2014,12
181601,0.628886,0.000000,0.178978,3.485443,0.0,1.766244,5.945369,0.0,0.0,0.0,...,0.000000,0.0,0.0,1.167099,4.774967,0.000000,31.434878,-14.364232,2014,12
181602,0.338524,0.004987,0.255840,3.468584,0.0,1.573873,2.304023,0.0,0.0,0.0,...,0.115988,0.0,0.0,0.627161,3.428957,0.010196,22.144878,-16.384232,2014,12

In [5]:
# import seaborn as sns
# sns.heatmap(df.iloc[:,:-4])

In [6]:
year_file = str(here('data', 'random_features', satellite, f'{file_name}.feather'))
df.to_feather(year_file)